### ISSUE TITLE
Showing Matching Values of Regex Without Attribute

### ISSUE THREAD

**Issue by shiote2** [tc3-japan/web-scraper#110]
Matching values of Regex without attribute input should match element text of Selector. Attribute is matched only when attribute is input. Please see below:
https://docs.google.com/presentation/d/16hRVS9bQbk7b9Oe0yOnyNrfHCGwur8GlRPfEb9lQeRU/edit#slide=id.g8d75ec6325_1_28

**Comment by birdofpreyru** [comment]
@shiote2 A little doubt here. Should I match the regex just against the _innerHTML_ of selected elements as is, without any extra trimming? That's how I did it now, and I see that in many cases the _innerHTML_ starts with newline and whitespace indentation, which is matched and shown in the tooltip as whitespaces. On one hand, it looks a bit weird in UI, on other hand it is probably what you want to see, if your scraper does the matching similarly.

**Comment by shiote2** [comment]
@birdofpreyru 
Could you use _innerText_? That's what we want to see it🙂
Thank you for considering!

**Comment by birdofpreyru** [comment]
Ok @shiote2, updated.

**Comment by shiote2** [comment]
@birdofpreyru 
Fixed. Thanks!
