### ISSUE TITLE
Group Selector for Purchase History Not Set

### ISSUE THREAD

**Issue by shiote2** [tc3-japan/web-scraper#113]
I found Group Selectors for both Purchase Order and Purchase Product of Purchase History are not set when selecting child elements. They used to work before this implementation. 

![image](https://user-images.githubusercontent.com/56425323/88661712-ee405a00-d113-11ea-98b9-4591c465d987.png)

Please check page 11, 18~31 in previous contest spec to see how it worked.
https://drive.google.com/file/d/1U4yxqMA2RjQeyfAAOZwYmbWZg1FOcNHU/view

**Comment by birdofpreyru** [comment]
I belive, fixed.

**Comment by shiote2** [comment]
Fixed. Thanks!
