### ISSUE TITLE
Script Remaining After Reloading

### ISSUE THREAD

**Issue by shiote2** [tc3-japan/web-scraper#114]
Reloading JSON from API does not overwrite Script checkbox. It occurs in Purchase History as well but not in Product Detail.

![image](https://user-images.githubusercontent.com/56425323/88665535-b89e6f80-d119-11ea-8a21-08dd02ad2623.png)

**Comment by birdofpreyru** [comment]
@shiote2 fixed

**Comment by shiote2** [comment]
@birdofpreyru 
Thanks!
Unfortunately Check button became not working😭
![image](https://user-images.githubusercontent.com/56425323/88797432-493e8380-d1de-11ea-87dc-1ac2b17380bb.png)

**Comment by birdofpreyru** [comment]
@shiote2 can you be more specific, what JSON you load, and what else you do? I just rapidly try to click on _Check_ of all kinds of Script fields in all pages, with and without reloading the data, and they all seem functional to me.

**Comment by shiote2** [comment]
@birdofpreyru 
Fixed. Thanks!
