### ISSUE TITLE
Warning in Chrome Extension Manager

### ISSUE THREAD

**Issue by shiote2** [tc3-japan/web-scraper#115]
![image](https://user-images.githubusercontent.com/56425323/88668717-f1d8de80-d11d-11ea-8f3a-b9136a97d008.png)

**Comment by birdofpreyru** [comment]
@shiote2 this is somewhat related to #108. I could not really reproduce that exact error (for some reason, my Chrome on Ubuntu seems fine about running `querySelector(..)` with empty selectors, but yeah once I realized that this, and other invalid selectors (_e.g._ if you remove one brace from some of `:nth-of-type(1)`), can crash the query, I wrapper the query into `try/catch`, and left this console warning just for the sake of debugging. On the UI side it acts now just like if nothing was matched by the query.

Do you want to do something else about it?

**Comment by shiote2** [comment]
@birdofpreyru 
Got it👍 It's just warning.
Thanks for checking.
Closed.
